nginx:
    image: "nginx:latest"
    volumes:
     - ./nginx.conf:/etc/nginx/nginx.conf
     - ./vhost:/etc/nginx/conf/vhost
     - ./dist:/dist
     - ./static:/static
    ports:
     - "80:80"
     - "443:443"
    links:
     - flask:flask

flask:
    image: "flask:latest"
    ports:
     - "5000:5000"
    volumes:
     - ../mysite/myblog:/mysite
    links:
     - mysql:mysql
    command: python wsgi.py

mysql:
    image: "mysql:latest"
    ports:
     - "3306:3306"
    command: /usr/local/mysql/bin/mysqld
